# Generated by Django 6.0.5 on 2026-05-12 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_countdown", "0004_alter_sitecountdown_long_description"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitecountdown",
            options={
                "ordering": ["-countdown_time"],
                "verbose_name": "Site shutdown countdown",
                "verbose_name_plural": "Site shutdown countdowns",
            },
        ),
        migrations.AlterField(
            model_name="sitecountdown",
            name="countdown_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time at which the site will be blocked",
                null=True,
                verbose_name="Countdown time",
            ),
        ),
        migrations.AlterField(
            model_name="sitecountdown",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="sitecountdown",
            name="long_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional longer description shown on the blocked page",
                verbose_name="Long description",
            ),
        ),
        migrations.AlterField(
            model_name="sitecountdown",
            name="maintenance_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when maintenance ends (optional). Leave empty for indefinite maintenance — the site will stay blocked until the countdown is removed.",
                null=True,
                verbose_name="Maintenance end",
            ),
        ),
        migrations.AlterField(
            model_name="sitecountdown",
            name="message",
            field=models.CharField(
                help_text="Short message shown in the page header (max 200 chars)",
                max_length=200,
                verbose_name="Short message",
            ),
        ),
        migrations.AlterField(
            model_name="sitecountdown",
            name="site",
            field=models.OneToOneField(
                help_text="Site to which this countdown applies",
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.site",
                verbose_name="Site",
            ),
        ),
        migrations.AlterField(
            model_name="sitecountdown",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
